server:
  port: 8080
spring:
  application:
    name: gridcapa-exporter
  rabbitmq:
    host: localhost
    port: 5672
    username: gridcapa
    password: gridcapa
  cloud:
    stream:
      default:
        group: cse-idcc-outputs
      bindings:
        consumeTaskDtoUpdate-in-0:
          destination: cse-idcc-task-updated
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1
        bindings:
          consumeTaskDtoUpdate-in-0:
            consumer:
              binding-routing-key: status
    function:
      definition: consumeTaskDtoUpdate

task-manager:
  base-url: http://localhost/cse/idcc/task-manager
  fetch-task:
    reties-number: 6
    interval-in-seconds: 10
ftp:
  host: localhost
  port: 21
  access-key: gridcapa
  secret-key: gridcapa
  remote-relative-destination-directory: /data/cse/idcc/outputs

logback:
  amqp:
    exchange: task-manager-logs-exchange
    routing-key: "#"
